stephendawsondev/jedi-academy

memory/memory.html
whack-a-droid/whack-a-droid.html
wordle/wordle.html

- create memory game folder
- create whack a droid game folder
- create wordle game folder

add new folder structure

---

wordle/wordle.css
wordle/wordle.html

Added container, and title, and board with some basic html and css.

Add basic html and css of the container, title, and board

---

js/script.js

This adds the initial local storage `gameData` object can be found in the inspector tools under **Application > Local Storage > Domain**.

add local storage functionality

---

wordle/wordle.js

added tiles to the game board of Wordle mini game

added tiles to the game board

---

wordle/wordle.css
wordle/wordle.html

Have added a modal tag for the How to Play section, and also added more css like the background-colour of the container/board and the text colour of the title.

Add a how to play modal tag to html, and add more css

---

wordle/wordle.js

-also added functionalities for backspace and enter buttons

added checkformatch function

---

index.html
js/index.js
js/script.js

- move index logic to index.js file
- add player name to local storage
- only prompt for name if none
- add firstTimePlayed to localStorage

update local storage settings:

---

wordle/wordle.js

-skip the letter if it has been marked correct

fixed a bug; color change when letter are correct

---

wordle/wordle.js

- added functionality to select random word for each game

added words and hints as a map

---

memory/memory.css
memory/memory.html

Add begin game button, score, timer and reset game function

Game Board functions

---

wordle/wordle.html
wordle/wordle.js

also moved the display box between keyboard and gameboard

added popup messages to the game

---

wordle/wordle.css
wordle/wordle.html
wordle/wordle.js

- made button arrangement horizontal 
-added popup msg for Enter key (on screen keyboard) when game lose

changed play again and back buttons arrangement

---

wordle/wordle.css
wordle/wordle.html

Please check the code in the html file, I removed one or 2 css things. It should be mostly ok now I think. Please let me know if there is anything else to change.

Merge conflict issue resolved for wordle game

---

README.md

Amend deployment, credits and collaborators sections on readme

---

team-page/team-page.css
team-page/team-page.html

Please take a look at this and tell me what you think. Some of the letters of the font are coming out as different letters as they are supposed to be! Still need info from some team members.

Add html and css, and some content to the team-page

---

css/style.css
index.html
js/results.js
js/script.js
results.html

created results logic so user can find out what jedi rank they have acheived in results.html

added results logic to results.js

---

README.md

Formattetd the readme so the links are clearer and a few other bits.

Format and make a few amendments to readme

---

js/script.js

Added youngling-padawan.mp3 code into the script.js

added youngling-padawan mp3 and code into script.js

---

wordle/wordle.html

bug : not changing the color of 1st row of keyboard when games go on

fixed the bug in onscreen keyboard

---

wordle/wordle.css

- also added bottom padding for buttons

changedbtton arrangemnet for mobile devises
